r0gue-io/pop-node

Cargo.toml, node/build.rs, node/src/chain_spec.rs, node/src/cli.rs, node/src/command.rs, node/src/main.rs, node/src/rpc.rs, node/src/service.rs, runtime/Cargo.toml, runtime/build.rs, runtime/src/assets_config.rs, runtime/src/contracts_config.rs, runtime/src/lib.rs, runtime/src/weights/block_weights.rs, runtime/src/weights/extrinsic_weights.rs, runtime/src/weights/paritydb_weights.rs, runtime/src/weights/rocksdb_weights.rs, runtime/src/xcm_config.rs
This merge request adds the following pallets:
- `pallet-nfts`
- `pallet-nfts-runtime-api`
- `pallet-nft-fractionalization`
- `pallet-assets`
- `pallet-scheduler` --> Requires `pallet-preimage`
Closes: #8
=> Add asset pallet suite + scheduler

networks/rococo.toml
Simply moves the `command` to launch a parachain to the `default_command` setting for the parachain. 
Note: This is primarily motivated by pop cli support and has not been tested with legacy zombienet.
=> chore: improve zombienet config

.github/workflows/build.yml
Grants permission to the workflow to annotate the checks with any clippy warnings.
=> ci: grant write permission to actions

pop-api/primitives/src/storage_keys.rs, runtime/src/extensions.rs
Adds test to ensure that read_state chain extension works.
Notes:
- added `MaxEncodedLen` to key types to use `env.read_as()`
- charges a db read for reading the specified key from contract memory, to be replaced once benchmarked
- charges a db read for obtaining the last relay block
- removed unnecessary `pub` modifiers
=> test(pop-api): read_state chain extension test

contracts/pop-api-examples/nfts/lib.rs, pop-api/primitives/src/storage_keys.rs, runtime/src/extensions.rs
Prerequisite: Merge https://github.com/r0gue-io/pop-node/pull/22 first
=> feat(pop-api): charge proper weights in chain-extension

Cargo.lock, contracts/pop-api-examples/nfts/lib.rs, pop-api/Cargo.toml, pop-api/primitives/Cargo.toml, pop-api/primitives/src/lib.rs, pop-api/primitives/src/storage_keys.rs, pop-api/src/lib.rs, pop-api/src/v0/mod.rs, pop-api/src/v0/nfts.rs, runtime/src/assets_config.rs, runtime/src/extensions.rs
Implements the remaining runtime calls that were listed, along with a few queries.
Notes: 
- Removes the offchain signing calls for now.
- Have not implemented those which require AccountId to be added to primitives (e.g. custom attribute). It results in a dependency mismatch between the runtime and that required by ink. Need to find a solution for this.
- Suggest moving `pop-api-primitives` to `pop-primitives` in a separate PR
=> feat(pop-api): further implementation of nfts api

integration-tests/Cargo.toml, integration-tests/src/lib.rs
Sets all dependencies as `dev-dependencies` so that they are not compiled in normal builds. Global `#![cfg(test)]` seems to ensure that all in crate are only compiled under tests.
=> build(integration-tests): fix to only build during tests

Cargo.lock, Cargo.toml, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
=> feat: async backing

runtime/src/extensions.rs
Use [`RelaychainDataProvider`](https://github.com/paritytech/polkadot-sdk/blob/ea458d0b95d819d31683a8a09ca7973ae10b49be/cumulus/pallets/parachain-system/src/lib.rs#L1715) to retrieve the relay chain block number instead.
=> fix(pop-api): read_state uses RelayChainDataProvider

integration-tests/src/lib.rs, pop-api/Cargo.toml, pop-api/examples/balance-transfer/Cargo.toml, pop-api/examples/nfts/Cargo.toml, pop-api/examples/place-spot-order/.gitignore, pop-api/examples/place-spot-order/Cargo.toml, pop-api/examples/place-spot-order/lib.rs, pop-api/examples/read-runtime-state/Cargo.toml, pop-api/src/lib.rs, runtime/src/extensions.rs
Also updates ink! deps to 5.0.0-rc3
=> feat: spot order contract

Cargo.toml
Fixes an issue when building via `-p pop-node` specifically.
=> build(deps): fix pop-runtime default features

integration-tests/src/chains/pop_network/genesis.rs, integration-tests/src/lib.rs, node/src/chain_spec.rs, runtime/src/lib.rs
Network now launches with zero total issuance, requiring a reserve transfer from the relay to get started. This will be automated with a pop up feature, but for now one can reserve transfer from relay to Pop with the following encoded calls:
- Send 100 UNIT to Alice on Pop
`0x630804000100098e0400010100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d04040000000b00407a10f35a0000000000`
- Send 100 UNIT to Bob on Pop
`0x630804000100098e04000101008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a4804040000000b00407a10f35a0000000000`
Commits:
- filter `balances::force*` calls to prevent minting of native token, ensuring network can only be funded from relay token
- removes endowments from chainspec 
- removes endowments from genesis within integration tests, updating …
=> feat: network token enforcement

Cargo.toml, integration-tests/src/chains/pop_network/genesis.rs, integration-tests/src/lib.rs, node/Cargo.toml, node/src/chain_spec.rs, node/src/command.rs, runtime/common/Cargo.toml, runtime/common/src/lib.rs, runtime/devnet/Cargo.toml, runtime/testnet/Cargo.toml
Various minor improvements identified during review, along with one fix of a regression in functionality caused by the split.
=> refactor: separate runtimes

Cargo.lock, Cargo.toml
Switches to crates.io dependencies.
=> build(deps): switch to crates.io dependencies

runtime/testnet/src/extensions.rs
Closes https://github.com/r0gue-io/pop-node/issues/54
Removes XCM use cases for contracts from testnet runtime.
=> refactor(pop-network): remove coretime use case from testnet

.github/workflows/release.yml, Cargo.lock, Cargo.toml, node/Cargo.toml
=> build: add release workflow

.github/workflows/lint-pr.yml
Adds a check for PR titles to ensure they comply with conventional commit spec. A step to towards semantic versioning of releases.
=> ci: add pr check for conventional commit spec compliance

.github/workflows/release.yml
Reworks the release workflow to include macOS binaries (Apple Silicon and x64), along with aarch64 on Linux.
Examples at https://github.com/r0gue-io/pop-node/releases/tag/test, where binary for each release is compressed and labelled using `pop-node-(target)(-cpu)` convention, making the files much smaller to download and more importantly, all use `pop-node` once extracted.
=> build(release): add macos support

pop-api/examples/balance-transfer/Cargo.toml, pop-api/examples/balance-transfer/lib.rs, pop-api/examples/nfts/Cargo.toml, pop-api/examples/nfts/lib.rs, pop-api/examples/place-spot-order/Cargo.toml, pop-api/examples/place-spot-order/lib.rs, pop-api/examples/read-runtime-state/Cargo.toml, pop-api/examples/read-runtime-state/lib.rs, runtime/devnet/src/extensions.rs, runtime/testnet/src/extensions.rs
Should be same as https://github.com/r0gue-io/pop-node/pull/79 but without the signing commit issues.
=> refactor: pop-api examples

pop-api/README.md
ditto
Please be hard on the feedback so we can make this perfect.
=> docs: add pop api documentation

scripts/fund-dev-accounts/README.md, scripts/fund-dev-accounts/main.rs, scripts/fund-dev-accounts/rococo_interface.rs
Updates the rococo interface as at Polkadot 1.11, along with setting the current para ids per relay.
Also updates the docs to use static ports so it is much quicker and easier.
=> chore: update codegen

runtime/devnet/src/extensions.rs, runtime/devnet/src/lib.rs, runtime/testnet/src/extensions.rs, runtime/testnet/src/lib.rs
Only removes old code in the runtime so that it can no longer be used on testnet until API complete. Removing the code in other crates will be done on the `api` branch as soon as it is rebased on this PR because it is very different and feels like I would have to do the job twice.
=> refactor: remove old api code

.chopsticks/README.md, .chopsticks/devnet.yml, .chopsticks/paseo.yml, .chopsticks/testnet.yml
Adds chopsticks config for testing of runtime upgrades.
=> chore: add chopsticks config

pallets/api/src/fungibles/mod.rs, pallets/api/src/fungibles/tests.rs, pop-api/integration-tests/contracts/fungibles/lib.rs, pop-api/integration-tests/src/fungibles/mod.rs, pop-api/integration-tests/src/local_fungibles.rs, pop-api/src/v0/assets/fungibles.rs, runtime/devnet/src/config/api.rs
Adds burn and mint to the fungibles use case.
Closes #98
=> feat: burn and mint

pallets/api/src/fungibles/mod.rs, pallets/api/src/fungibles/tests.rs, pop-api/examples/balance-transfer/lib.rs, pop-api/examples/nfts/lib.rs, pop-api/examples/place-spot-order/lib.rs, pop-api/examples/read-runtime-state/lib.rs, pop-api/integration-tests/contracts/.gitignore, pop-api/integration-tests/contracts/create_token_in_constructor/Cargo.toml, pop-api/integration-tests/contracts/create_token_in_constructor/lib.rs, pop-api/integration-tests/contracts/fungibles/lib.rs, pop-api/integration-tests/src/fungibles/mod.rs, pop-api/integration-tests/src/fungibles/utils.rs, pop-api/integration-tests/src/lib.rs, pop-api/integration-tests/src/local_fungibles.rs, pop-api/src/v0/assets/fungibles.rs, runtime/devnet/src/config/api.rs
Implements the functionality for asset management:
Additional changes:
- added `DEPRECATED` to old examples and automatic formatting was applied.
- refactored the integration tests helper functions in a separate file `utils.rs`.
The dispatchables required to destroy an asset but not added to the api are `destroy_accounts`, `destroy_approvals` and `finish_destroy`. They have not been included in the api because they do not have to be signed by the owner of the asset and cause complexities in the implementation*. Asset owners (in this case via a contract) are required to complete the steps of destroying an asset via pallet assets in stead of the contract (as it is normally also the case). Only starting the destroying process of an asset has to be initiated by the contract if it is the owner …
=> feat: asset management

extension/src/lib.rs, runtime/devnet/src/config/api.rs, runtime/devnet/src/config/contracts.rs
Alternative design of the PR: https://github.com/r0gue-io/pop-node/pull/163
- Removing the `Config` trait so there is no relationship between the `Runtime` and the extension. 
- Types need to be passed to the generic extension type `ApiExtension`. 
This alternative approach removes all the connections with the `Runtime`, every configuration will be on the level of the `ApiExtension`
=> refactor: remove config and add generic extension type

Cargo.lock, node/Cargo.toml, runtime/testnet/Cargo.toml, runtime/testnet/src/config/contracts.rs, runtime/testnet/src/lib.rs
Adds a missing migration necessary for `testnet-runtime` `0.4.0`.
Bumps spec version of testnet-runtime to `00_04_00`
=> fix: missing migration

README.md
_Small fix:_ I was testing pop-node locally and noticed that the `README` was pointing to a config file that doesn't exist anymore. Just updated it.
=> docs(readme): fix instruction in the README

.github/ISSUE_TEMPLATE/release_tracking.md
Based on the previous checklist we have used for 0.4.0 - https://github.com/r0gue-io/pop-node/issues/221
I have created this template that we can re-use for future releases of both, node and runtime, until we start moving to a move automated, CI self contained process.
=> docs: release tracking issue template

extension/src/decoding.rs, extension/src/functions.rs, extension/src/matching.rs, extension/src/mock.rs, extension/src/tests/contract.rs, extension/src/tests/mod.rs, extension/src/tests/utils.rs
Refactored the tests so that all the functionality is tested in a more accumulative way. Starting as small as possible and then bubbling up, also reusing helper functions for weight that help readers understand how it works.
=> refactor: extension unit tests

Cargo.lock, runtime/testnet/Cargo.toml, runtime/testnet/src/lib.rs
This is a small version bump to 0.4.1 for adding XCM ExecuteFilter=Everything.
=> chore(testnet): bump version to 0.4.1

extension/src/functions.rs, extension/src/mock.rs, pallets/api/src/extension.rs, runtime/devnet/src/config/api/versioning.rs
Refactors to allow fallible conversion, required simply to eliminate the `unimplemented!()` statements in the runtime when converting to a versioned result/error.
=> refactor: fallible conversion

Cargo.lock, extension/src/functions.rs, extension/src/matching.rs, extension/src/mock.rs, pallets/api/src/extension.rs, pop-api/src/lib.rs, pop-api/src/v0/mod.rs, primitives/Cargo.toml, primitives/src/lib.rs, runtime/devnet/src/config/api/versioning.rs
For tests `pallet/api/src/extension.rs` see #272
=> refactor: encoding scheme

pop-api/examples/fungibles/lib.rs, pop-api/integration-tests/contracts/create_token_in_constructor/Cargo.toml, pop-api/integration-tests/contracts/fungibles/Cargo.toml, pop-api/integration-tests/src/fungibles/mod.rs, pop-api/integration-tests/src/fungibles/utils.rs, pop-api/integration-tests/src/lib.rs, pop-api/src/lib.rs, pop-api/src/v0/fungibles.rs, pop-api/src/v0/mod.rs, primitives/src/lib.rs, runtime/devnet/src/config/assets.rs
Contains all changes coming from comments for `pop-api` in #132 . Please not that in the comments I used #279 (incorrect) and #280. They both count for this PR.
Changes include:
- Example refactor
- refactor (pop api): ChainExtensionMethodApi type + small doc changes.
- refactor (integration tests): 
1. remove clone
2. terminology to token & token_id
3. refactor env_logger
4. refactor helper functions from pallet assets
5. probably some more small ones.
=> refactor: api integration tests

.github/workflows/ci.yml, .github/workflows/release.yml
Related: #270 
Note: 270 is the base branch. Please only review:
- .github/workflows/ci.yml
- .github/workflows/release.yml
No other files changed.
Updates the CI to _also_  build the runtimes with `--features ismp` enabled. It also modifies the release CI to only build one selected runtime or the runtime for a release (see below). If the runtime is devnet, it will build the node with `--features ismp`.
**This means the release CI will now only build ONE runtime.** Considering this is for releases, I do not see a reason we would need to build several runtimes. A testnet and mainnet release should be distinct. There is no reason to have a devnet release. There is also the option for `none`, which skips the srtool build altogether.
When a release is published, the CI will build that …
=> feat(CI): add ismp feature to CI, and choosing runtime for release

pallets/api/src/fungibles/mod.rs, pallets/api/src/fungibles/tests.rs, pop-api/examples/fungibles/lib.rs, pop-api/integration-tests/src/fungibles/mod.rs
`Fungibles::decrease_allowance()` saturating_sub the value, it should `checked_sub` and throw an error instead. Hence, we don't have to handle `InsufficientAllowance` on the contract side.
Benefit of this approach is to make the implementation of PSP22 example contract cleaner.
=> feat: return `UnApproved` in `decrease_allowance` instead of `saturating_sub`

pop-api/integration-tests/Cargo.toml
https://github.com/r0gue-io/pop-node/issues/313
=> fix(ci): api-integration-tests

pallets/api/src/fungibles/mod.rs, pallets/api/src/fungibles/tests.rs, pop-api/integration-tests/contracts/fungibles/lib.rs, pop-api/integration-tests/src/fungibles/mod.rs, pop-api/integration-tests/src/fungibles/utils.rs, pop-api/src/v0/fungibles/mod.rs
The psp22 standard returns an `Option<String>`. In stead of having the contract needing to add additional logic, we handle it in the pallet.
=> feat: token name & symbol return `Option`

runtime/devnet/src/lib.rs
Required change for drink test environment. This PR has to be merged to have the reviewers test #300
=> chore: timestamp settings for tests

pallets/revive/src/wasm/runtime.rs, pallets/revive/uapi/src/host.rs, pallets/revive/uapi/src/host/riscv32.rs
Required for a compatible implementation of self.env().caller() for ink!
=> feat(revive): add `to_account_id` host function for converting from a `h160` to `h256` account

pallets/nfts/src/benchmarking.rs, pallets/nfts/src/common_functions.rs, pallets/nfts/src/features/approvals.rs, pallets/nfts/src/features/create_delete_collection.rs, pallets/nfts/src/features/transfer.rs, pallets/nfts/src/lib.rs, pallets/nfts/src/tests.rs, pallets/nfts/src/types.rs, pallets/nfts/src/weights.rs
Refactoring the `Allowances` storage item to map the key as `(collection, owner)` with `ApprovalsOf<T, I>` as value. This change will reuse an existing `ApprovalOf` struct to provide the expiration feature for the collection approvals.
=> refactor(nfts): mapping with `ApprovalsOf` in the `Allowances` storage item

Cargo.lock, pallets/api/Cargo.toml, pallets/api/src/messaging/mod.rs, pallets/api/src/messaging/transports/ismp.rs, pallets/api/src/messaging/transports/xcm.rs, pop-api/examples/messaging/lib.rs, pop-api/integration-tests/Cargo.toml, pop-api/integration-tests/contracts/messaging/lib.rs, pop-api/integration-tests/src/messaging.rs, pop-api/src/lib.rs, pop-api/src/v0/messaging/ismp.rs, pop-api/src/v0/messaging/mod.rs, pop-api/src/v0/messaging/xcm.rs, runtime/devnet/src/config/api/mod.rs, runtime/devnet/src/config/xcm.rs
Adds optional callback specification when using the messaging API. See the messaging contract within pop-api/integration-tests/contracts for usage.
=> feat(messaging): callbacks

pop-api/Cargo.toml, pop-api/examples/fungibles/Cargo.toml, pop-api/examples/fungibles/tests.rs, pop-api/integration-tests/contracts/create_token_in_constructor/Cargo.toml, pop-api/integration-tests/contracts/fungibles/Cargo.toml, pop-api/src/v0/fungibles/errors.rs
In v5.0 there was an ugly warning from the linter which is fixed in v5.1. Also good to uplift the version.
=> chore: ink v5.1

pallets/nfts/src/tests.rs
Refactors some of the test by separating the e.g. approve_collection_transfer and force_approve_collection_transfer, and while doing so found some small improvements.
=> refactor: tests for collection approval

pallets/api/src/fungibles/mod.rs, pallets/api/src/fungibles/tests.rs, pallets/api/src/mock.rs
Quick PR to refactor the order of `Read` implementation in fungibles pallet to keep the structure of pallet consistent with others.
=> refactor: reorder `Read` impl in fungibles pallet

pallets/api/src/fungibles/tests.rs
Minor refactor to avoid code duplication in nonfungible pallet test
=> refactor: reuse `WeightInfo` in nonfungibles pallet test

Cargo.lock, Cargo.toml, runtime/mainnet/Cargo.toml, runtime/mainnet/src/apis.rs, runtime/mainnet/src/lib.rs
Add various improvements to the mainnet runtime, including:
- More config tests:  https://github.com/r0gue-io/pop-node/commit/5fd13cb70e76014eaa55e3c4510e79ebe567398c
- refactor to apis module: https://github.com/r0gue-io/pop-node/commit/3f86cd5a926a28448777c9aec061759f91d16d24
- add XCM runtime apis: https://github.com/r0gue-io/pop-node/commit/a6880e429507f16c6b6a196696a282bc7d5b7720
Recommend reviewing individual commits to more easily see the changes to the APIs.
supersedes https://github.com/r0gue-io/pop-node/pull/426
Credit to @evilrobot-01 as well as some of this code is based on prior work from him.
=> feat(mainnet): add XCM APIs, config tests, refactor mod

node/src/command.rs, runtime/mainnet/src/config/mod.rs, runtime/mainnet/src/config/system.rs, runtime/mainnet/src/lib.rs
Creates **system** config module including:
- `frame_system`
Notable configuration items are:
- SS58
`pub const SS58Prefix: u16 = 0;`
---
- `frame_system`
`extensionsWeightInfo` needs to be configured after benchmark is run. Configured to use default weights a the moment.
No calls area filtered.
No permanent migrations included at genesis.
```rust
type BaseCallFilter = Everything;
type ExtensionsWeightInfo = (); // Needs to be updated after benchmarks
type Lookup = AccountIdLookup<Self::AccountId, ()>;
type SingleBlockMigrations = ();
```
---
- `parachain_system`
```rust
type CheckAssociatedRelayNumber = RelayNumberMonotonicallyIncreases;
type ReservedDmpWeight = MAXIMUM_BLOCK_WEIGHT.saturating_div(4);;
type ReservedXcmpWeight = MAXIMUM_BLOCK_WEIGHT.saturating_div(4);;
type SelectCore = …
```
=> refactor(mainnet): system config

runtime/mainnet/src/config/xcm.rs
XCM fees apply universally and are not waived for any specific location in mainnet runtime.
[sc-1353]
[sc-2205]
=> fix(xcm): remove waived locations

integration-tests/src/chains/pop_network/genesis.rs, integration-tests/src/chains/pop_network/mod.rs, integration-tests/src/lib.rs
The tests need to be improved in general but refactored it so that there is no mainnet specific code to a runtime generic test.
=> refactor: integration tests mainnet xcm

runtime/mainnet/src/config/utility.rs
Improves how deposits are presented in utility config for mainnet runtime.
=> chore(utility): make deposit calc explicit.

runtime/mainnet/src/benchmarks.rs, runtime/mainnet/src/lib.rs
Moves benchmarks to its own file.
=> refactor(benchmakrs): benchmarks mod in its own file

networks/mainnet.toml, node/src/chain_spec.rs, node/src/command.rs, runtime/mainnet/src/apis.rs, runtime/mainnet/src/config/mod.rs, runtime/mainnet/src/genesis.rs, runtime/mainnet/src/lib.rs
Based on #472 
Moves genesis configuration for mainnet into the runtime.
These are the different spec that will use the mainnet runtime. These are the ones we can pass to the node via `--chain  <spec>`.
```rust
/// A development chain running on a single node, using the `mainnet` runtime.
pub const MAINNET_DEV: &str = "pop-dev";
/// Configures a local chain running on multiple nodes for testing purposes, using the `mainnet`
/// runtime.
pub const MAINNET_LOCAL: &str = "pop-local";
/// A live chain running on multiple nodes, using the `mainnet` runtime.
pub const MAINNET: &str = "pop";
```
---
[sc-2373]
=> refactor(mainnet): use genesis presets for mainnet runtime.

.github/workflows/release.yml, Cargo.lock, node/Cargo.toml, node/chain_specs/testnet/paseo.raw.json, runtime/testnet/src/config/mod.rs
This PR should only be merged after #482 . I've pushed these changes outside of #482 such that we can keep an explicit commit in history about these changes.
-  [x] Needs to be rebased after 482 has been merged.
Changes:
- Bumps node version after having introduced ISMP into testnet runtime in #482.
- Updates the CI release workflow to activate the ISMP feature for testnet releases.
- Pushes a more actual version of paseo relay chain in [e3a72e1](https://github.com/r0gue-io/pop-node/pull/484/commits/e3a72e1859a8fa60d0570d39b9b9e6a516bac28e). The node can sync the relay without problems.
- Removes "alpha" from the node crate version.
=> chore(node): `pop-node v0.3.0`

.github/workflows/release.yml
- Moves away from using `upload-artifact@v3` as it is [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). Uses v4 instead.
- Adds `NODE_BUILD_OPTS` to build-node task: https://github.com/r0gue-io/pop-node/pull/488/commits/c1e0ee03680cf88591f4afea7145db6157ab5461
- `Install packages` runs `apt-get update` https://github.com/r0gue-io/pop-node/pull/488/commits/b7b30f49fd6aa3277aa909f59a2ddbc3696ae6d9
- Downgrades srtool to 0.8.0 https://github.com/r0gue-io/pop-node/pull/488/commits/0a1c92eda04c487f0d6992e057800ea871648985
- Provides unique names for the artifacts being used on upload-artifact@v4 by appending the sha256 of the binary. [073885c](https://github.com/r0gue-io/pop-node/pull/488/commits/073885c7fa2df68c7a69ab75a0cf44a3ed9c2ff8). …
=> fix(ci): different fixes for release workflow

Cargo.lock, pallets/api/src/messaging/deposits.rs, pallets/api/src/messaging/mod.rs, pallets/api/src/messaging/tests.rs, pallets/api/src/messaging/transports/ismp.rs, pallets/api/src/mock.rs
This was heavily dependant on reasoning about how weights are charged to the contract env.
Taking a deposit for the callback weight allows us to delay the paying of fees and provide an artificial gas metering.
This is secure still as the callback weight is passed to the contract env as a gas limit. It also means we will not charge in the macro the callback weight like originally thought. 
- I have removed the `spare_weight_creditor` and defaulted it to the origin, if developers want to specify in the future where the unused gas should go its a simple change.
- `FeeAccount` has been added to the config, it should be set as the collator pot or reward pot as its where we will manually put the fees for callbacks
- Where there is a call back on any of the initialising extrinsics (ismp_get, …
=> Refund any unused callback weight

pallets/api/src/messaging/benchmarking.rs, pallets/api/src/messaging/mod.rs, pallets/api/src/messaging/test_utils.rs, pallets/api/src/messaging/tests.rs, pallets/api/src/messaging/transports/ismp.rs, pallets/api/src/messaging/weights.rs, pallets/api/src/mock.rs, runtime/devnet/src/weights/messaging_weights.rs
As mentioned in the telegram allow people to top up callback gas for requesting messages.
Was low hanging fruit so thought id get it in before the ismp_weight issue call.
[sc-3601]
=> feat(messaging): callback gas topup

pallets/api/src/messaging/mod.rs, pallets/api/src/messaging/tests.rs, pallets/api/src/messaging/transports/ismp.rs, runtime/devnet/src/config/api/mod.rs
The aim of this PR is to address the use of blockspace when: 
- A callback is executed
- A dispatchables weight is not accounted for
A refactor has been done to split apart `handle_callback_result` into: 
- process_callback_weight
- deposit_event
- manage_fees
The new parameter `static_weight_adjustment` is intended to provide flexibility between different protocols that handle weight and fees in different ways. 
For ismp: The weights are charged in the normal extrinsic route, hence no static_weight_adjustment is required. 
for xcm: Since we are dispatching a call plainly, outside the normal extrinsic flow, we must charge weight manually hence, we include the weight of the response extrinsic and the callback executor as a static_weight_adjustment.
=> chore(messaging): final weight revision

runtime/devnet/src/config/assets.rs, runtime/devnet/src/config/proxy.rs, runtime/devnet/src/lib.rs, runtime/mainnet/src/config/assets.rs, runtime/mainnet/src/config/proxy.rs, runtime/mainnet/src/config/utility.rs, runtime/testnet/src/config/assets.rs, runtime/testnet/src/config/proxy.rs, runtime/testnet/src/config/utility.rs
Changes for [polkadot-sdk#5723](https://github.com/paritytech/polkadot-sdk/pull/5723).
This PR adds the ability for these pallets to specify their source of the block number.
They have been all configured to depend on the local block number.
Note that `pallet_nfts` in devnet is using a local forked version of the pallet, not depending on the newer version upstream.
Tests to ensure these configurations have been added to mainnet runtime.
---
[sc-3547]
=> chore: `BlockNumberProvider` for multisig, nfts & proxy

runtime/mainnet/src/config/assets.rs, runtime/mainnet/src/config/proxy.rs, runtime/mainnet/src/config/xcm.rs
As per [polkadot-sdk#5899](https://github.com/paritytech/polkadot-sdk/pull/5899).
This PR substitutes all occurrences of `AccountKeyring` with `Sr25519Keyring`.
---
[sc-3547]
=> chore: substitute `AccountKeyring` with `Sr25519Keyring`

runtime/common/src/weights/pallet_utility.rs
As per [polkadot-sdk#6321](https://github.com/paritytech/polkadot-sdk/pull/6321).
Adds weights for the new extrinsic `if_else` in `pallet_utility`. The weights added here have been copied from the linked PR. Benchmarks should be eventually run again to get proper results for this node.
---
[sc-3547]
=> chore: weight for `pallet_utility` `if_else` extrinsic

runtime/mainnet/src/apis.rs
As per [polkadot-sdk#6459](https://github.com/paritytech/polkadot-sdk/pull/6459).
The `query_weight_to_asset_fee` function of the `XcmPaymentApi` was trying to convert versions wrong. Resulting in all calls made with lower versions failing.
The version conversion is now done correctly and the previous failing calls will now succeed.
---
[sc-3547]
=> fix: version conversion in `XcmPaymentApi::query_weight_to_asset_fee`

runtime/mainnet/src/apis.rs, runtime/testnet/src/lib.rs
As per [polkadot-sdk#6608](https://github.com/paritytech/polkadot-sdk/pull/6608).
`eth_transact` and `bare_eth_transact` api have been updated to use `GenericTransaction` directly as this is what is used by `eth_estimateGas` and `eth_call`.
It also updates `ReviveApi::call` & `ReviveApi::instantiate` to comply with the change in type for parameter `storage_deposit_limit` in `Revive::bare_call` and `Revive::bare_instantiate`.
Note that devnet runtime doesn't have `pallet_revive` at this point. Hence no changes are required for it.
---
[sc-3547]
=> chore: update `eth_transact` and `bare_eth_transact` apis

runtime/mainnet/src/config/revive.rs, runtime/testnet/src/config/contracts.rs
As per [polkadot-sdk#6689](https://github.com/paritytech/polkadot-sdk/pull/6689).
Implement `EthGasEncoder` in pallet_revive for testnet and mainnet runtimes.
Includes a unit tests to ensure the configuration for `EthGasEncoder` is `()` in mainnet.
---
[sc-3547]
=> chore: impl `EthGasEncoder` for `pallet_revive`

rust-toolchain.toml
As per [polkadot-sdk#7008](https://github.com/paritytech/polkadot-sdk/pull/7008).
We can change the toolchain we are using from `wasm32-unknown-unknown` to [`wasm32v1-none`](https://doc.rust-lang.org/beta/rustc/platform-support/wasm32v1-none.html).
Note the following - [source](https://github.com/paritytech/polkadot-sdk/blob/0c0d4ceba45a70f4e8dc40b1ee0cfae1fd759454/substrate/utils/wasm-builder/src/lib.rs#L103):
> //! Wasm builder requires the following prerequisites for building the Wasm binary:
> //! - Rust >= 1.68 and Rust < 1.84:
> //!   - `wasm32-unknown-unknown` target
> //!   - `rust-src` component
> //! - Rust >= 1.84:
> //!   - `wasm32v1-none` target
=> chore: change toolchain to wasm32v1-none

Cargo.lock, Cargo.toml, extension/Cargo.toml, extension/src/decoding.rs, extension/src/environment.rs, extension/src/lib.rs, pallets/api/Cargo.toml, pallets/api/src/extension.rs, pallets/api/src/fungibles/mod.rs, pallets/api/src/lib.rs, pallets/api/src/messaging/mod.rs
As per [polkadot-sdk#7043](https://github.com/paritytech/polkadot-sdk/pull/7043).
This PR substitutes the remaining dependencies on `sp-std`, all of them bringing `Vec` into scope. Now `Vec` is brought from `alloc` instead.
=> refactor: remove dependencies on `sp-std`

runtime/mainnet/src/apis.rs, runtime/mainnet/src/config/revive.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/config/contracts.rs, runtime/testnet/src/lib.rs
As per [polkadot-sdk#7163](https://github.com/paritytech/polkadot-sdk/pull/7163), [polkadot-sdk#7166](https://github.com/paritytech/polkadot-sdk/pull/7166) and [polkadot-sdk#7167](https://github.com/paritytech/polkadot-sdk/pull/7167).
This PR eliminates the Debug buffer from pallet-revive and implements tracing support to ReviveApi, the concrete added apis are:
- `trace_block`
- `trace_tx`
- `trace_call`
=> chore(revive): remove Debug buffer and add tracing support

runtime/mainnet/src/apis.rs, runtime/testnet/src/lib.rs
As per [polkadot-sdk #7281](https://github.com/paritytech/polkadot-sdk/pull/7281).
This PR implementes the runtime api `ReviveApi::block_gas_limit` for testnet and mainnet runtimes.
=> feat: implement `ReviveApi::block_gas_limit` api

runtime/mainnet/src/config/revive.rs, runtime/testnet/src/config/contracts.rs
As per [polkadot-sdk#7198](https://github.com/paritytech/polkadot-sdk/pull/7198).
This PR implements the new `FindAuthor` type in `pallet_revive::Config` to follow `pallet_authorship` `FindAuthor` configuration.
=> chore(revive): implement FindAuthor

runtime/testnet/src/lib.rs
As per [polkadot-sdk#7230](https://github.com/paritytech/polkadot-sdk/pull/7230).
Testnet needs a migration for `pallet-revive` in case a new version of the runtime is to be deployed.
=> docs: note required missing revive migration for testnet

runtime/devnet/src/config/xcm.rs, runtime/mainnet/src/config/xcm.rs, runtime/testnet/src/config/xcm.rs
As per [polkadot-sdk#7234](https://github.com/paritytech/polkadot-sdk/pull/7234).
This PR implements the `EventEmitter` trait of the XCM executor for all the runtimes, allowing configurable event emission.
=> feat(xcm): implement XcmEventEmitter

runtime/devnet/src/lib.rs, runtime/mainnet/src/config/utility.rs, runtime/testnet/src/config/utility.rs
Changes for [polkadot-sdk#7441](https://github.com/paritytech/polkadot-sdk/pull/7441).
This PR adds the ability for this pallet to specify its source of the block number.
`pallet_scheduler` has been configured to depend on the local block number.
A test to ensure this configurations has been added to mainnet runtime.
---
[sc-3547]
=> chore: add `BlockNumberProvider` to `pallet_scheduler`

runtime/devnet/src/lib.rs, runtime/mainnet/src/config/collation.rs, runtime/testnet/src/config/collation.rs
As per [polkadot-sdk#7581](https://github.com/paritytech/polkadot-sdk/pull/7581).
Implement `DisablingStrategy` for `pallet_session` in every runtime.
Note that the migration included upstream is not a requirement for `pop-node`.
=> feat(session): implement `DisablingStrategy`

runtime/common/src/weights/pallet_multisig.rs
As per [polkadot-sdk#7700](https://github.com/paritytech/polkadot-sdk/pull/7700).
This PR introduces weights for the new extrinsic in pallet-multisig, `poke_deposit`. These weights have been copied from westend runtime upstream and benchmarks should be run before releasing any new runtime version.
=> chore: weights for `pallet_multisig::poke_deposit`

runtime/common/src/weights/pallet_proxy.rs
As per [polkadot-sdk#7801](https://github.com/paritytech/polkadot-sdk/pull/7801).
This PR introduces weights for the new extrinsic in pallet-proxy, `poke_deposit`. These weights have been copied from Westend runtime upstream and benchmarks should be run before releasing any new runtime version.
=> chore: weights for `pallet_proxy::pole_deposit`

runtime/devnet/src/lib.rs, runtime/mainnet/src/apis.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
As per [polkadot-sdk#4722](https://github.com/paritytech/polkadot-sdk/pull/4722).
This PR introduces runtime view functions in all runtimes. It also implements the runtime api `runtime_api::RuntimeViewFunction`, such that users can access state via view functions defined in the pallets present in our runtimes.
=> feat: implement pallet view functions

runtime/devnet/src/config/assets.rs, runtime/mainnet/src/config/assets.rs, runtime/testnet/src/config/assets.rs
As per [polkadot-sdk#4530](https://github.com/paritytech/polkadot-sdk/pull/4530).
This PR implements `Holder` for `pallet-assets` in every runtime. `pallet-assets-holder` is not introduced in this PR, hence I've kept `Holder` configured to `()`.
=> chore: impl `Holder` for `pallet_assets`

node/src/service.rs
As per [polkadot-sdk#6400](https://github.com/paritytech/polkadot-sdk/pull/6400).
This PR removes the unnecessary `network_starter`.
As discussed upstream this seems to be an old artifact of an already closed issue.
=> refactor: remove unnecessary `network_starter`

node/src/service.rs
As per [polkadot-sdk#8040](https://github.com/paritytech/polkadot-sdk/pull/8040).
This includes the missing max_pov_percentage to the aura parameters of our lookahead collator.
The PoV usage is increased by default to 85%.
=> chore: add `max_pov_percentage` to `AuraParams`

integration-tests/src/chains/asset_hub/genesis.rs, integration-tests/src/chains/relay/genesis.rs, runtime/devnet/src/genesis.rs, runtime/mainnet/src/genesis.rs, runtime/testnet/src/genesis.rs
As per [polkadot-sdk#6267](https://github.com/paritytech/polkadot-sdk/pull/6267).
This PR configures the genesis of devnet, testnet and mainnet runtime to include the missing element in pallet_balances'' GenesisConfig.
=> chore: Configurable number of genesis accounts in pallet_balances

Cargo.lock, Cargo.toml, pallets/api/src/fungibles/mod.rs, pallets/api/src/messaging/mod.rs, pallets/api/src/messaging/transports/ismp.rs, pallets/api/src/mock.rs, pallets/api/src/nonfungibles/mod.rs, pallets/motion/src/mock.rs, pallets/motion/src/tests.rs, pallets/nfts/src/migration.rs, pallets/nfts/src/tests.rs, pallets/nfts/src/types.rs, runtime/common/src/lib.rs
As per [polkadot-sdk#7267](https://github.com/paritytech/polkadot-sdk/pull/7627).
This PR derives `DecodeWithMemTracking` for:
- [`ProxyType`](https://github.com/r0gue-io/pop-node/commit/0ffb6b5e1a5fb359090547e161f1ebb49455e868)
=> refactor: derive `DecodeWithMemTracking`

Cargo.lock, pop-api/Cargo.lock, pop-api/Cargo.toml, pop-api/integration-tests/contracts/create_token_in_constructor/Cargo.lock, pop-api/integration-tests/contracts/fungibles/Cargo.lock, pop-api/integration-tests/contracts/messaging/Cargo.lock, pop-api/integration-tests/contracts/nonfungibles/Cargo.lock, pop-api/integration-tests/src/nonfungibles/utils.rs, pop-api/src/v0/nonfungibles/types.rs
There is an issue in the nonfungible API that when user calls `api::nonfungibles::create`, it throws `Contract Decode Failed`. Reason to that is the mismatched type in the `price` field of `MintSettings` in the runtime and in the API crate. 
- Remove the balance `u32` type in the nonfungibles api crate. Use the `primitives::Balance` type instead.
- Update all tests in the nonfungible integration tests to test with the min / max value of the data types instead of `None`.
=> fix: nonfungible api mismatched balance type

.github/actions/init/action.yml
Rust caching is currently failing due to 'Cache service responded with 422' and 'This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP.'
=> ci: bump rust-cache version to latest

networks/devnet.toml
Improves the default logging levels within the `devnet` network config file, correcting a typo which means that nothing from api is currently emitted.
=> chore(devnet): improve default logging

networks/devnet.toml, networks/mainnet.toml
Resolves two issues spotted whilst using the network config files for testing:
- asset-hub was using rococo runtime instead of paseo within devnet.toml
- pop args for mainnet were invalid based on functionality available within mainnet runtime
=> chore: improve network config files

Cargo.lock, runtime/devnet/Cargo.toml, runtime/devnet/src/config/contracts.rs, runtime/devnet/src/lib.rs
Adds revive to the devnet runtime.
This is to ensure devs can deploy revive contracts on a local devnet.
Consider the upcoming PRs:
- 2503 upgrade
- Sync devnet with mainnet (includes removal of pallet contracts)
- Add api to revive
=> feat(devnet): revive

.github/workflows/ci.yml
Ensures there is only ever one active workflow running per PR. 
Already implemented at https://github.com/r0gue-io/pop-cli/blob/main/.github/workflows/ci.yml#L13.
=> ci: enable concurrency controls

.github/workflows/ci.yml, pop-api/examples/fungibles/Cargo.toml, pop-api/examples/fungibles/tests.rs
Update to use the latest version of pop-drink that is bumped to stable2503, compatible with the current codebase of pop-node. Requires https://github.com/r0gue-io/pop-drink/pull/30 to be merged first.
=> chore(api/examples/fungible): bump drink version

rust-toolchain.toml
The release of rust 1.87.0 introduced issues on CI making tests involving instantiation of wasm smart contracts fail.
Pinning version to stable 1.86.0 instead of latest stable until resolved.
=> fix(ci): pin stable-1.86 version

.github/workflows/release.yml
Adds `production` profile to sr-tool runtime build flow in releases.
Aside from other benefits of running building with the production profile the main driver for this change has been pursuing a smaller size in the resulting wasm blob.
The resulting uncompressed runtime should result in a size around `10.1 MB` based on [a prior build](https://github.com/r0gue-io/pop-node/actions/runs/15047519554).
=> refactor(ci): build runtimes using production profile

Cargo.lock, Cargo.toml, integration-tests/src/lib.rs, pop-api/Cargo.lock
This PR is based on `al3mart/sync-polkadot-stable2503` but ideally merged into main after the sync with 2503 is merged.
Will leave this PR pointing to merge into `al3mart/sync-polkadot-stable2503` then rebase onto main such that the diff is easier to inspect.
The relevant changes applied from [polkadot-stable2503-1](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-stable2503-1) have been:
- Dependencies update via `psvm -v polkadot-stable2503-1`.
- Fix of integration tests as per [`polkadot-sdk#7913`](https://github.com/paritytech/polkadot-sdk/pull/7913).
Note that different weights are being used within `para_to_system_para_sender_assertions` to accommodate for the difference in xcm configurations between runtimes.  Once all runtimes are in sync these should again be back …
=> chore: sync with `polkadot-stable2503-1`

Cargo.lock, runtime/testnet/Cargo.toml, runtime/testnet/src/config/collation.rs, runtime/testnet/src/config/system.rs, runtime/testnet/src/lib.rs
These changes prepare a new release for pop's testnet runtime.
Mainly lowering `MinEligibleCollators` to `1` and removing the already released migrations.
The reason behind the value of `1` as the minimum amount of eligible collators is that to reduce the number of collators in the set we need the following condition to compute true:
```
ensure!(
Self::eligible_collators() > T::MinEligibleCollators::get(),
Error::<T>::TooFewEligibleCollators
);
```
Given no candidates at the moment and only `3` invulnerables. `elegible_collators` (candidates + invulnerables) won't be greater than the current value set for `MinEligibleCollators`.
By setting this value to `1` we will be able to modify the number of collators in the future without blockers if needed.
=> chore(testnet): v0.5.4
